# Application config
spring.application.name=MiniCoreBankingSystem
server.port=8085

# DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/banking_demo
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Twilio API details for OTP verification
twilio.accountSid=AC43ad935fa382fb21a6aa767f66c305ae
twilio.authToken= 05fedd745f5953be354cde6f55164c4d
twilio.verifyServiceSid=VA5ec2dec8d79e2c183d27edb08dcd9ff9

# Razorpay Credentials
razorpay.api.key=rzp_test_J6aspcdNViF6Yi
razorpay.api.secret=3HdOBPOIIV5NiEW2ERH9bovj

# Email Credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=snehalbchavan11@gmail.com
#spring.mail.password=djay upnv wwwo eyfc
spring.mail.username=manjushabchavan123@gmail.com
spring.mail.password=uqom ttev otbb mmxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true